version: '3'

services:
  web:
    image: $LOCAL_IMAGE_ID
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: ""
    ports:
      - 80

  integration-tests:
    build: ./tests/integration-tests
    depends_on:
      - web
